repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.2.3
        hooks:
          # removes trailing whitespace
        - id: trailing-whitespace
          # linting tool config: .flake8
        - id: flake8
        # code formatter
        # linting tool config: pyproject.toml
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.7
        # linting tool config: .pylintrc
    -   repo: https://github.com/pre-commit/mirrors-pylint
        rev: v2.3.1
        hooks:
        -   id: pylint
            args: ["--ignore-patterns=test*,migrations/*.py", "--py3k"]
