"""empty message

Revision ID: 15e241c7996a
Revises: cf85e2018b06
Create Date: 2020-10-23 22:34:47.034097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15e241c7996a"
down_revision = "cf85e2018b06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command",
        sa.Column("_id", sa.Integer(), nullable=False),
        sa.Column("command", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("_id"),
        sa.UniqueConstraint("command"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("command")
    # ### end Alembic commands ###
