"""empty message

Revision ID: 18375435b043
Revises: 15e241c7996a
Create Date: 2020-10-24 00:12:10.938048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18375435b043"
down_revision = "15e241c7996a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "command", sa.Column("bot_name", sa.String(length=100), nullable=True)
    )
    op.add_column("command", sa.Column("cmd", sa.String(length=100), nullable=True))
    op.drop_constraint("command_command_key", "command", type_="unique")
    op.create_unique_constraint(None, "command", ["cmd"])
    op.drop_column("command", "command")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "command",
        sa.Column(
            "command", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "command", type_="unique")
    op.create_unique_constraint("command_command_key", "command", ["command"])
    op.drop_column("command", "cmd")
    op.drop_column("command", "bot_name")
    # ### end Alembic commands ###
