"""empty message

Revision ID: cf85e2018b06
Revises: 7e0ddd763344
Create Date: 2020-10-23 22:31:00.582386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf85e2018b06"
down_revision = "7e0ddd763344"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command",
        sa.Column("_id", sa.Integer(), nullable=False),
        sa.Column("command", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("_id"),
        sa.UniqueConstraint("command"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("command")
    # ### end Alembic commands ###
